import type { Tool } from "@modelcontextprotocol/sdk/types.js";

import type { OpenApiIndex, OpenApiOperationInfo } from "./openapi.js";
import {
  hasUsefulOutputSchema,
  hasUsefulSchema,
  mergeSchemaMetadata,
  methodNameForTool,
  schemaToTypeScriptDeclaration,
  typeBaseForTool,
  type JsonSchema,
} from "./schema.js";

type SchemaSource = "mcp" | "mcp+openapi" | "openapi" | "observed-mcp" | "unknown";
type OpenApiMatch = "exact" | "create-task-batch-family" | "none";

export interface GeneratedTool {
  annotations?: Tool["annotations"];
  description?: string;
  destructive: boolean;
  inputOptional: boolean;
  inputSchema: JsonSchema;
  inputSchemaSource: SchemaSource;
  methodName: string;
  name: string;
  openapi?: {
    match: OpenApiMatch;
    method: string;
    operationId: string;
    path: string;
  };
  outputSchema?: JsonSchema;
  outputSchemaSource: SchemaSource;
  readOnly: boolean;
  typeBase: string;
}

export interface GeneratedArtifacts {
  manifest: Record<string, unknown>;
  referenceMarkdown: string;
  schemas: Record<string, unknown>;
  signatures: string;
  tools: GeneratedTool[];
}

export interface GenerateArtifactsOptions {
  mcpEndpoint: string;
  observedOutputSchemas?: Record<string, JsonSchema>;
  openapiOperationCount?: number;
  openapiUrl?: string;
  server?: unknown;
  tools: Tool[];
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const jsonSchema = (value: unknown): JsonSchema | undefined =>
  isRecord(value) ? value : undefined;

const requiredProperties = (schema: JsonSchema): string[] =>
  Array.isArray(schema.required)
    ? schema.required.filter((value): value is string => typeof value === "string")
    : [];

const toolInputIsOptional = (schema: JsonSchema): boolean =>
  requiredProperties(schema).length === 0;

const matchOpenApiOperation = (
  toolName: string,
  openApiIndex: OpenApiIndex | undefined,
): { info?: OpenApiOperationInfo; match: OpenApiMatch } => {
  const exact = openApiIndex?.operations.get(toolName);
  if (exact) return { info: exact, match: "exact" };
  if (toolName.startsWith("CreateTaskBatch_")) {
    const createTaskBatch = openApiIndex?.operations.get("CreateTaskBatch");
    if (createTaskBatch) return { info: createTaskBatch, match: "create-task-batch-family" };
  }
  return { match: "none" };
};

const schemaSource = (
  primarySource: "mcp" | "openapi" | "unknown",
  supplemented: boolean,
): SchemaSource => {
  if (primarySource === "mcp" && supplemented) return "mcp+openapi";
  return primarySource;
};

const generatedToolFromMcpTool = (
  tool: Tool,
  openApiIndex: OpenApiIndex | undefined,
  observedOutputSchemas: Record<string, JsonSchema> | undefined,
): GeneratedTool => {
  const openapi = matchOpenApiOperation(tool.name, openApiIndex);
  const rawMcpInput = jsonSchema(tool.inputSchema);
  const rawMcpOutput = jsonSchema(tool.outputSchema);
  const openapiInput = openapi.info?.inputSchema;
  const openapiOutput = openapi.info?.outputSchema;
  const observedOutput = observedOutputSchemas?.[tool.name];

  const inputResult = rawMcpInput
    ? mergeSchemaMetadata(rawMcpInput, openapiInput)
    : openapiInput
      ? { schema: openapiInput, supplemented: false }
      : {
          schema: { type: "object", properties: {}, additionalProperties: false },
          supplemented: false,
        };

  const inputSource =
    rawMcpInput && hasUsefulSchema(rawMcpInput)
      ? schemaSource("mcp", inputResult.supplemented)
      : openapiInput
        ? "openapi"
        : "unknown";

  const outputResult =
    rawMcpOutput && hasUsefulOutputSchema(rawMcpOutput)
      ? mergeSchemaMetadata(rawMcpOutput, openapiOutput)
      : undefined;
  const outputSchema = outputResult?.schema ?? openapiOutput ?? observedOutput;
  const outputSource = outputResult
    ? schemaSource("mcp", outputResult.supplemented)
    : openapiOutput
      ? "openapi"
      : observedOutput
        ? "observed-mcp"
        : "unknown";

  const destructive =
    tool.annotations?.destructiveHint === true || tool.name.startsWith("CreateTaskBatch_");
  const readOnly = tool.annotations?.readOnlyHint === true && !destructive;

  return {
    annotations: tool.annotations,
    description: tool.description,
    destructive,
    inputOptional: toolInputIsOptional(inputResult.schema),
    inputSchema: inputResult.schema,
    inputSchemaSource: inputSource,
    methodName: methodNameForTool(tool.name),
    name: tool.name,
    openapi: openapi.info
      ? {
          match: openapi.match,
          method: openapi.info.method,
          operationId: openapi.info.operationId,
          path: openapi.info.path,
        }
      : undefined,
    outputSchema,
    outputSchemaSource: outputSource,
    readOnly,
    typeBase: typeBaseForTool(tool.name),
  };
};

const header = `/* eslint-disable */
// Generated by scripts/generate-nonce-sdk.ts.
// Source of truth: MCP tools/list; OpenAPI and observed read-only MCP outputs only fill missing schema metadata.
`;

const optionsType = (tool: GeneratedTool): string =>
  tool.destructive ? "DestructiveCallOptions" : "ReadonlyCallOptions";

const methodSignature = (tool: GeneratedTool): string => {
  const inputType = `${tool.typeBase}Input`;
  const outputType = `${tool.typeBase}Output`;
  const input = tool.inputOptional ? `input?: ${inputType}` : `input: ${inputType}`;
  const options = tool.destructive
    ? `options: ${optionsType(tool)}`
    : `options?: ${optionsType(tool)}`;
  return `  ${tool.methodName}(${input}, ${options}): Promise<${outputType}>`;
};

const requiredInputSummary = (tool: GeneratedTool): string | undefined => {
  const required = requiredProperties(tool.inputSchema);
  if (required.length === 0) return undefined;
  return `required: ${required.join(", ")}`;
};

const renderSignatures = (tools: GeneratedTool[]): string => {
  const declarations = tools.flatMap((tool) => [
    schemaToTypeScriptDeclaration(`${tool.typeBase}Input`, tool.inputSchema).declaration,
    schemaToTypeScriptDeclaration(`${tool.typeBase}Output`, tool.outputSchema).declaration,
  ]);

  const definitions = tools.map((tool) => ({
    destructive: tool.destructive,
    methodName: tool.methodName,
    name: tool.name,
    readOnly: tool.readOnly,
  }));

  return `${header}
export interface CallOptions {
  signal?: AbortSignal
  timeoutMs?: number
}

export type ReadonlyCallOptions = CallOptions

export interface DestructiveCallOptions extends CallOptions {
  confirmDestructive: true
  confirmation: string
}

${declarations.join("\n")}
export const nonceToolDefinitions = ${JSON.stringify(definitions, null, 2)} as const

export interface NonceMcpClient {
  close(): Promise<void>
${tools.map(methodSignature).join("\n")}
}
`;
};

const renderReferenceMarkdown = (
  tools: GeneratedTool[],
  options: GenerateArtifactsOptions,
): string => {
  const lines = [
    "# Tool Signatures",
    "",
    "Generated from Nonce MCP `tools/list`; OpenAPI and observed read-only MCP outputs only fill missing schema metadata.",
    "",
    `- MCP endpoint: \`${options.mcpEndpoint}\``,
    ...(options.openapiUrl ? [`- OpenAPI supplement: ${options.openapiUrl}`] : []),
    `- Tool count: ${tools.length}`,
    "",
    "This file is a compact index. Before writing task code, open `assets/runtime/src/generated/tool-signatures.ts` and read the exact `<MethodType>Input` and `<MethodType>Output` interfaces for every method you call.",
    "",
    "Do not call the OpenAPI endpoint for business operations. OpenAPI is only used here to supplement missing schema metadata; runtime calls must go through the local SDK.",
    "",
    "Import the SDK from the runtime entrypoint and use the generated interfaces for input and output shapes.",
    "",
    "```ts",
    'import { createNonceClient } from "../../assets/runtime/src/index.ts"',
    "",
    'const client = await createNonceClient({ profile: "default" })',
    "try {",
    '  const farms = await client.listFarms({ workspace_id: "..." })',
    "} finally {",
    "  await client.close()",
    "}",
    "```",
    "",
    "## Methods",
    "",
  ];

  for (const tool of tools) {
    const input = tool.inputOptional
      ? `input?: ${tool.typeBase}Input`
      : `input: ${tool.typeBase}Input`;
    const options = tool.destructive
      ? `options: DestructiveCallOptions`
      : `options?: ReadonlyCallOptions`;
    const markers = [
      tool.readOnly ? "read-only" : undefined,
      tool.destructive ? "destructive" : undefined,
      `input: ${tool.inputSchemaSource}`,
      `output: ${tool.outputSchemaSource}`,
      requiredInputSummary(tool),
      tool.openapi?.operationId ? `openapi: ${tool.openapi.operationId}` : undefined,
    ].filter(Boolean);
    lines.push(
      `- \`${tool.methodName}(${input}, ${options}): Promise<${tool.typeBase}Output>\` - ${tool.name} (${markers.join(", ")})`,
    );
  }

  return `${lines.join("\n")}\n`;
};

export const generateArtifacts = (
  options: GenerateArtifactsOptions,
  openApiIndex?: OpenApiIndex,
): GeneratedArtifacts => {
  const tools = options.tools.map((tool) =>
    generatedToolFromMcpTool(tool, openApiIndex, options.observedOutputSchemas),
  );
  const manifestTools = tools.map((tool) => ({
    annotations: tool.annotations,
    description: tool.description,
    destructive: tool.destructive,
    inputSchemaSource: tool.inputSchemaSource,
    methodName: tool.methodName,
    name: tool.name,
    openapi: tool.openapi,
    outputSchemaSource: tool.outputSchemaSource,
    readOnly: tool.readOnly,
    typeBase: tool.typeBase,
  }));

  return {
    manifest: {
      generatedBy: "scripts/generate-nonce-sdk.ts",
      mcpEndpoint: options.mcpEndpoint,
      openapiOperationCount: options.openapiOperationCount,
      openapiUrl: options.openapiUrl,
      server: options.server,
      sourcePriority: ["mcp-tools-list", "openapi-supplement", "observed-readonly-mcp-output"],
      toolCount: tools.length,
      tools: manifestTools,
    },
    referenceMarkdown: renderReferenceMarkdown(tools, options),
    schemas: {
      generatedBy: "scripts/generate-nonce-sdk.ts",
      tools: Object.fromEntries(
        tools.map((tool) => [
          tool.name,
          {
            input: tool.inputSchema,
            inputSchemaSource: tool.inputSchemaSource,
            output: tool.outputSchema,
            outputSchemaSource: tool.outputSchemaSource,
          },
        ]),
      ),
    },
    signatures: renderSignatures(tools),
    tools,
  };
};
