/* eslint-disable */
// Generated file. Do not edit by hand.
// Source of truth: checked Nonce method definitions; supplemental schemas only fill missing metadata.

export interface ListFarmsInput {
  workspace_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
}
export interface ListFarmsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: Farm[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface Farm {
  /**
   * Farm Id (uuid generated by nonce system)
   */
  id: string
  /**
   * Farm Name
   */
  name: string | null
  /**
   * Farm Description
   */
  description: string | null
  /**
   * Farm Location
   */
  location: string | null
  /**
   * Workspace Id
   */
  workspace_id: string
  /**
   * Farm operational status
   */
  status: "running" | "shutdown" | "leasing" | "maintenance" | "decommissioning" | "decommissioned"
  /**
   * Whether the farm is archived
   */
  archived: boolean
  /**
   * Hosting fee (electricity price) in USD per kWh
   */
  hosting_fee: number | null
}
export interface ListMinersInput {
  workspace_id: string
  farm_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Agent Id (uuid generated by nonce system)
   */
  agent_id?: string
  /**
   * Miner sn/hashboard sn/power supply sn/controller sn.(single value)
   */
  sn?: string
  /**
   * Filter miners by MAC address
   */
  mac?: string
  /**
   * Filter miners by status.
   * Accepts both run status (`online`, `stale`) and preset tags (`archived`, `maintenance`, `retired`, `off_rack`, `transit`).
   * Run status and tags are independent axes — filtering by `online` does NOT exclude miners carrying tags.
   * For new clients prefer `tags` for tag filtering and `status` for connectivity-state filtering.
   * Supports multiple values separated by `,` (e.g., "online,stale") or multiple query parameters (e.g., "status=online&status=stale").
   * Available statuses:
   * - online: Miner is actively mining and connected
   * - offline: Miner is not connected or powered off
   * - stale: Miner data is stale (no recent updates)
   * - archived: (Asset) Miner has been archived
   * - off_rack: (Asset) Miner is removed from rack
   * - transit: (Asset) Miner is in transit
   * - maintenance: (Asset) Miner is under maintenance
   * - retired: (Asset) Miner has been retired
   * - error: Deprecated. Use anomaly_filters.
   * - low_hashrate: Deprecated. Use hashrate_realization range.
   * - overheated: Deprecated. Use anomaly_filters=temperature.
   * - overpower: Deprecated. Use anomaly_filters=power.
   * - underpower: Deprecated. Use anomaly_filters=power.
   * - overclocking: Deprecated. Use mining_modes_in with overclocking presets.
   */
  status?: (
    | "online"
    | "offline"
    | "stale"
    | "sleep"
    | "unknown"
    | "archived"
    | "off_rack"
    | "transit"
    | "maintenance"
    | "retired"
    | "error"
    | "low_hashrate"
    | "overheated"
    | "overpower"
    | "underpower"
    | "overclocking"
  )[]
  /**
   * Filter miners by tags (operator-managed labels). Overlap match — a miner matches if it carries any of the values.
   * Preset values: `maintenance`, `retired`, `off_rack`, `transit`, `archived`, plus free-form custom tags.
   * Supports multiple values separated by `,` or multiple query parameters.
   */
  tags?: string[]
  /**
   * Unstable filter. `true` returns only miners with non-null `unstable_reason` (mac/sn unreliable). Omit, null, or false to include unstable miners.
   */
  unstable?: boolean
  /**
   * Abnormal axis (the whole `anomaly_flags` bitmask, not a specific type).
   * `true` = any anomaly bit set (anomaly_flags <> 0) — the overview "abnormal" scope.
   * `false` = no anomaly bits (anomaly_flags = 0) — the fault-free scope behind "healthy"/"sleep".
   * Omit to include both. Prefer this over OR-ing all `anomaly_filters` for the abnormal aggregate.
   */
  has_anomaly?: boolean
  /**
   * Filter miners by anomaly type (OR semantics — returns miners matching ANY of the specified types).
   * Available values: fan, power, temperature, hashboard, network, firmware, unknown, control_board, pool, low_hashrate.
   * Corresponds to bits in the anomaly_flags bitmask field on each miner.
   * Accepts repeated array (anomaly_filters[]=fan&anomaly_filters[]=power), comma-separated string (anomaly_filters=fan,power), or single value (anomaly_filters=fan).
   */
  anomaly_filters?: (
    | "fan"
    | "power"
    | "temperature"
    | "hashboard"
    | "network"
    | "firmware"
    | "unknown"
    | "control_board"
    | "pool"
    | "low_hashrate"
  )[]
  /**
   * Lower bound of hashrate realization rate (actual / expected). 1.0 = 100%. Miners with NULL or 0 expected_hashrate are excluded.
   */
  hashrate_realization_min?: number
  /**
   * Upper bound of hashrate realization rate. No hard cap (allows >1 for overclocked miners).
   */
  hashrate_realization_max?: number
  /**
   * Filter miners by mining_mode value (OR semantics — returns miners matching ANY of the specified modes).
   * Accepts repeated array (mining_modes_in[]=high&mining_modes_in[]=power_tuning), comma-separated string (mining_modes_in=high,power_tuning), or single value (mining_modes_in=high).
   */
  mining_modes_in?: string[]
  /**
   * Filter miners by IPv4 ranges. A miner matches if its IP falls into any of the provided ranges.
   * Each item accepts one of three forms:
   * - single address (e.g. `192.168.1.5`)
   * - CIDR (e.g. `192.168.1.0/24`)
   * - hyphen range (e.g. `192.168.1.1-192.168.1.254`, inclusive)
   * Supports multiple values separated by `,` or repeated query parameters.
   */
  ip_ranges?: string[]
}
export interface ListMinersOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: Miner[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface Miner {
  /**
   * Miner identifier
   */
  id: string
  /**
   * Farm this miner belongs to
   */
  farm_id: string
  /**
   * Workspace (tenant) identifier
   */
  workspace_id: string
  /**
   * Hardware serial number
   */
  serial_number: string | null
  /**
   * Manufacturer (e.g. Bitmain, MicroBT)
   */
  make: string
  /**
   * Hardware model (e.g. S19 Pro, M50S)
   */
  model: string | null
  /**
   * Current IP address
   */
  ip: string
  /**
   * MAC address
   */
  mac: string
  /**
   * Whether the miner is actively hashing
   */
  is_mining: boolean
  /**
   * Run status (system-managed). Values: online | stale.
   */
  status: string
  /**
   * Operator-managed labels (multi-value). Presets: maintenance | retired | off_rack | transit | archived, plus free-form custom tags. Empty when none.
   */
  tags?: string[]
  /**
   * Deprecated; always null. Operator labels moved to `tags`.
   */
  ops_status: string | null
  /**
   * Current power/performance mode
   */
  mining_mode: string
  /**
   * Real-time hashrate in H/s
   */
  hashrate: number | null
  /**
   * Expected hashrate in H/s
   */
  expected_hashrate: number | null
  /**
   * Real-time power consumption in watts
   */
  power: number | null
  /**
   * Average board temperature in celsius
   */
  temp: number | null
  /**
   * Energy efficiency in J/TH
   */
  efficiency: number | null
  /**
   * Bitmask of active anomalies. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
   */
  anomaly_flags?: number
  /**
   * Uptime in seconds
   */
  uptime: number | null
  /**
   * Last heartbeat timestamp (ISO 8601)
   */
  last_updated_at: string | null
  /**
   * Total reboots aggregated from daily miner_metrics over the default 7-day window. Null when no metrics have been computed yet. >= 10 in 7 days is considered high-frequency.
   */
  reboot_count: number | null
  /**
   * Reboots where pre-reboot uptime was < 10 min (boot cycling), aggregated over the default 7-day window. Null when no metrics have been computed yet. High ratio (> 50% of reboot_count) suggests hardware fault.
   */
  low_uptime_reboot_count: number | null
}
export interface SearchMinersInput {
  workspace_id: string
  farm_id: string
  /**
   * Miner ID filter. Supports exact match (`eq`) or set membership (`in`).
   */
  id?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * String filter operators. Provide at least one operator.
   */
  agent_id?: {
    eq?: string
    contains?: string
  }
  /**
   * String filter operators. Provide at least one operator.
   */
  sn?: {
    eq?: string
    contains?: string
  }
  /**
   * String filter operators. Provide at least one operator.
   */
  mac?: {
    eq?: string
    contains?: string
  }
  /**
   * Run status filter. Accepted values: `online`, `stale`.
   */
  status?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * Tag filter (operator-managed labels). Overlap match. Preset values: `maintenance`, `retired`, `off_rack`, `transit`, `archived`, plus free-form custom tags.
   */
  tags?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * Unstable filter. `true` returns only miners with non-null `unstable_reason`. Omit to include both stable and unstable miners.
   */
  unstable?: boolean
  /**
   * **Deprecated** — legacy combined filter. Use `status` and `tags` instead. Values are auto-routed to the matching axis. Note: run-state and tags are independent — filtering by a run-state value (e.g. `online`) does not exclude miners carrying tags. Will be removed in a future major version.
   */
  lifecycle_statuses?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * **Deprecated** — accepted for backward compatibility but ignored at runtime. Use `anomaly_filters` (anomaly bitmask) or `hashrate_realization` (ratio range) instead.
   */
  health_statuses?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * Filter miners by IPv4 ranges. A miner matches if its IP falls into any of the provided ranges. Each item accepts one of: single address `192.168.1.5`, CIDR `192.168.1.0/24`, or hyphen range `192.168.1.1-192.168.1.254`. At most 10 ranges per request.
   */
  ip_ranges?: string[]
  page?: number
  limit?: number
}
export interface SearchMinersOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: Miner[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface GetMinerStatsInput {
  workspace_id: string
  farm_id: string
}
export interface GetMinerStatsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  data: {
    theo: number | null
    total: number
    by_type: {
      healthy: number
      abnormal: number
      sleep: number
      stale: number
    }
    by_abnormal_type: {
      hashboard: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      temperature: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      fan: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      network: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      pool: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      power: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      control_board: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      firmware: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      low_hashrate: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
      unknown: {
        count: number
        also_has: {
          [k: string]: unknown
        }
      }
    }
    mining_mode: {
      mode: string
      count: number
    }[]
    miner_model: {
      model: string | null
      count: number
      theoretical_hashrate: number | null
    }[]
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface ListFarmMetricsHistoryInput {
  workspace_id: string
  farm_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Date in YYYY-MM-DD format
   */
  from_date: string
  /**
   * Date in YYYY-MM-DD format
   */
  to_date: string
  /**
   * Time resolution of the returned metrics.
   * - `day` (default): full daily metric set (pool / agent hashrate, online miners, BTC earnings, electricity).
   * - `hour` / `10min`: hashrate-only subset (period, pool hashrate, online / offline miner counts) aggregated from raw 10-minute samples.
   * Sub-day query windows are bounded: `10min` up to 7 days, `hour` up to 60 days. `day` is unbounded.
   */
  granularity?: "day" | "hour" | "10min"
}
export interface ListFarmMetricsHistoryOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: (FarmMetricHistory | FarmSubDayMetricHistory)[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface FarmMetricHistory {
  /**
   * Id (uuid generated by nonce system)
   */
  id: string
  /**
   * Farm Id (uuid generated by nonce system)
   */
  farm_id: string
  /**
   * Workspace Id
   */
  workspace_id: string
  /**
   * The period timestamp for this metric record
   */
  period: string
  pool: {
    /**
     * Hashrate value from Pool in H/s
     */
    hashrate: number | null
    /**
     * Number of online miners from pool
     */
    online_miners: number | null
  }
  agent: {
    /**
     * Hashrate value from Agent in H/s
     */
    hashrate: number | null
    /**
     * Number of online miners from agent
     */
    online_miners: number | null
  }
  finance: {
    /**
     * Earning in BTC
     */
    earning_btc: number | null
  }
  electricity: {
    /**
     * Agent-reported daily energy consumption in kWh
     */
    agent_energy: number | null
    /**
     * Estimated daily electricity cost based on agent energy (USD)
     */
    agent_electricity_cost: number | null
    /**
     * Estimated daily energy consumption based on pool hashrate and theo efficiency in kWh
     */
    pool_energy: number | null
    /**
     * Estimated daily electricity cost based on pool energy (USD)
     */
    pool_electricity_cost: number | null
    /**
     * Theoretical daily energy consumption based on farm worker specs in kWh
     */
    theo_energy: number | null
    /**
     * Theoretical daily electricity cost based on theo energy (USD)
     */
    theo_electricity_cost: number | null
  }
}
export interface FarmSubDayMetricHistory {
  /**
   * The period timestamp for this metric record
   */
  period: string
  pool: {
    /**
     * Hashrate value from Pool in H/s
     */
    hashrate: number | null
    /**
     * Number of online miners from pool
     */
    online_miners: number | null
    /**
     * Number of offline miners from pool
     */
    offline_miners: number | null
  }
}
export interface ListFarmEnergyHistoryInput {
  workspace_id: string
  farm_id: string
  /**
   * End time (ISO 8601). Defaults to now.
   */
  end_time?: string
  /**
   * Start time (ISO 8601). Defaults to 7 days ago.
   */
  start_time?: string
}
export interface ListFarmEnergyHistoryOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  data: {
    energy_summary: {
      theo_power: number | null
      theoEfficiency: number | null
      theo_total_energy: number | null
      theo_total_electricity_cost: number | null
      theo_avg_margin: number | null
      agent_avg_hashrate: number | null
      agent_avg_power: number | null
      agent_total_energy: number | null
      agent_avg_efficiency: number | null
      agent_total_est_electricity_cost: number | null
      agent_avg_margin: number | null
      pool_avg_hashrate: number | null
      pool_avg_power: number | null
      pool_total_energy: number | null
      pool_total_est_electricity_cost: number | null
      pool_avg_margin: number | null
      total_earning_btc: number | null
      total_earning_usd: number | null
    }
    energy_metrics: {
      period: string
      theo_energy: number | null
      theo_electricity_cost: number | null
      theo_margin: number | null
      agent_hashrate: number | null
      agent_power: number | null
      agent_energy: number | null
      agent_efficiency: number | null
      agent_est_electricity_cost: number | null
      agent_margin: number | null
      pool_hashrate: number | null
      pool_power: number | null
      pool_energy: number | null
      pool_est_electricity_cost: number | null
      pool_margin: number | null
      earning_btc: number | null
      earning_usd: number | null
    }[]
    power_metrics: {
      period: string
      pool_power: number | null
      agent_power: number | null
    }[]
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface ListMinerHistoryInput {
  workspace_id: string
  farm_id: string
  miner_id: string
  /**
   * Start time for the history data in ISO 8601 format with timezone offset.
   */
  from_time: string
  /**
   * End time for the history data in ISO 8601 format with timezone offset.
   */
  to_time: string
  /**
   * Time resolution of the returned snapshots.
   * - `10min`: max range 1 day (144 data points). Requires miner_id (single-miner queries only).
   * - `hour` (default): max range 7 days (168 data points).
   * - `day`: max range 90 days (90 data points).
   * - `week`: max range 365 days (52 data points).
   */
  granularity?: "10min" | "hour" | "day" | "week"
}
export interface ListMinerHistoryOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: {
    /**
     * Miner Id
     */
    miner_id: string
    /**
     * Start of the time range (ISO 8601)
     */
    from: string
    /**
     * End of the time range (ISO 8601)
     */
    to: string
    /**
     * Time resolution of the returned snapshots. Values: 10min | hour | day | week.
     */
    granularity: "10min" | "hour" | "day" | "week"
    /**
     * Time-series data points within the requested range.
     */
    snapshots: {
      /**
       * The period timestamp for this metric record
       */
      period: string
      /**
       * Hashrate value in H/s
       */
      hashrate: number | null
      /**
       * Power consumption in watts
       */
      wattage: number | null
      /**
       * Temperature in Celsius
       */
      temp: number | null
      /**
       * Uptime in seconds
       */
      uptime: number | null
      /**
       * Bitmask of active anomalies. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
       */
      anomaly_flags: number | null
    }[]
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface GetMinerTasksInput {
  workspace_id: string
  farm_id: string
  miner_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Miner task name
   */
  task_name?:
    | "agent.scan.create"
    | "agent.ip_diagnosis.create"
    | "agent.self.update"
    | "miner.system.reboot"
    | "miner.log.get"
    | "miner.light.update"
    | "miner.power_mode.update"
    | "miner.pool.update"
    | "miner.pool.lock"
    | "miner.firmware.update"
    | "miner.tags.update"
    | "miner.record.delete"
    | "miner.rack_location.update"
  /**
   * Task execution status. `created` = enqueued but not yet picked up by an agent; `queuing` = accepted by the agent and waiting in its local queue; `pending` = actively executing on the miner; `succeed` = finished successfully; `failed` = finished with an error; `timed_out` = exceeded its execution deadline; `cancelled` = aborted before completion.
   */
  status?: "created" | "queuing" | "pending" | "succeed" | "failed" | "timed_out" | "cancelled"
  /**
   * Start time for task history in ISO 8601 format with timezone offset. Must be within the last 7 days. Defaults to 7 days ago if not provided
   */
  from_time?: string
  /**
   * End time for task history in ISO 8601 format with timezone offset. Must be within the last 7 days. Defaults to now if not provided
   */
  to_time?: string
}
/**
 * Represents an entity that performs actions in the system (user, API key, or system)
 */
export type Actor = {
  [k: string]: unknown
} | null
export interface GetMinerTasksOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTask[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
/**
 * A task execution record for a single miner
 */
export interface MinerTask {
  /**
   * Miner task ID
   */
  task_id: string
  /**
   * Miner task batch ID
   */
  batch_id: string
  /**
   * Miner task name
   */
  task_name:
    | "agent.scan.create"
    | "agent.ip_diagnosis.create"
    | "agent.self.update"
    | "miner.system.reboot"
    | "miner.log.get"
    | "miner.light.update"
    | "miner.power_mode.update"
    | "miner.pool.update"
    | "miner.pool.lock"
    | "miner.firmware.update"
    | "miner.tags.update"
    | "miner.record.delete"
    | "miner.rack_location.update"
  /**
   * Task execution status. `created` = enqueued but not yet picked up by an agent; `queuing` = accepted by the agent and waiting in its local queue; `pending` = actively executing on the miner; `succeed` = finished successfully; `failed` = finished with an error; `timed_out` = exceeded its execution deadline; `cancelled` = aborted before completion.
   */
  status: "created" | "queuing" | "pending" | "succeed" | "failed" | "timed_out" | "cancelled"
  /**
   * Task parameters (JSON)
   */
  params: {
    [k: string]: unknown
  } | null
  /**
   * Error details if task failed (JSON)
   */
  error: {
    [k: string]: unknown
  } | null
  /**
   * Task execution result (JSON)
   */
  result: {
    [k: string]: unknown
  } | null
  created_by: Actor
  /**
   * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
   */
  created_at: string
  /**
   * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
   */
  updated_at: string
}
export interface ListMinerRebootEventsInput {
  workspace_id: string
  farm_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Filter by miner ID
   */
  miner_id?: string
  /**
   * Start time filter. Defaults to 7 days ago if not provided.
   */
  from_time?: string
  /**
   * End time filter. Defaults to now if not provided.
   */
  to_time?: string
}
export interface ListMinerRebootEventsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: {
    /**
     * Reboot event ID
     */
    id: string
    /**
     * Workspace ID
     */
    workspace_id: string
    /**
     * Farm ID
     */
    farm_id: string
    /**
     * Miner ID
     */
    miner_id: string
    /**
     * Miner IP address at time of query
     */
    ip: string
    /**
     * Miner hardware model (e.g. S19 Pro)
     */
    model: string | null
    /**
     * Miner manufacturer (e.g. Bitmain)
     */
    make: string
    /**
     * Miner serial number
     */
    serial_number: string | null
    /**
     * Detection period (ISO 8601)
     */
    period: string
    /**
     * Uptime before reboot (seconds)
     */
    pre_uptime: number | null
    /**
     * Uptime after reboot (seconds)
     */
    post_uptime: number | null
    /**
     * Hashrate before reboot (H/s)
     */
    pre_hashrate: number | null
    /**
     * Hashrate after reboot (H/s)
     */
    post_hashrate: number | null
    /**
     * Pre-reboot snapshot collection time (ISO 8601)
     */
    pre_period: string | null
    /**
     * Post-reboot snapshot collection time (ISO 8601)
     */
    post_period: string | null
    /**
     * Power consumption before reboot (watts)
     */
    pre_wattage: number | null
    /**
     * Power consumption after reboot (watts)
     */
    post_wattage: number | null
    /**
     * Average board temperature before reboot (celsius)
     */
    pre_temp: number | null
    /**
     * Average board temperature after reboot (celsius)
     */
    post_temp: number | null
    /**
     * Anomaly bitmask before reboot. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
     */
    pre_anomaly_flags: number | null
    /**
     * Anomaly bitmask after reboot. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
     */
    post_anomaly_flags: number | null
    /**
     * Mining mode before reboot (e.g. normal, sleep, low)
     */
    pre_mining_mode: string | null
    /**
     * Mining mode after reboot (e.g. normal, sleep, low)
     */
    post_mining_mode: string | null
    /**
     * Record creation time (ISO 8601)
     */
    created_at: string | null
    /**
     * Average hashrate 30–5 minutes before reboot (H/s); null when the window has no history
     */
    before_avg_hashrate: number | null
    /**
     * Average hashrate 15–60 minutes after reboot (H/s); null when the window has no history
     */
    after_avg_hashrate: number | null
  }[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface GetMinerRebootEventsInput {
  workspace_id: string
  farm_id: string
  miner_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Start time filter. Defaults to 7 days ago if not provided.
   */
  from_time?: string
  /**
   * End time filter. Defaults to now if not provided.
   */
  to_time?: string
}
export interface GetMinerRebootEventsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: {
    /**
     * Reboot event ID
     */
    id: string
    /**
     * Workspace ID
     */
    workspace_id: string
    /**
     * Farm ID
     */
    farm_id: string
    /**
     * Miner ID
     */
    miner_id: string
    /**
     * Miner IP address at time of query
     */
    ip: string
    /**
     * Miner hardware model (e.g. S19 Pro)
     */
    model: string | null
    /**
     * Miner manufacturer (e.g. Bitmain)
     */
    make: string
    /**
     * Miner serial number
     */
    serial_number: string | null
    /**
     * Detection period (ISO 8601)
     */
    period: string
    /**
     * Uptime before reboot (seconds)
     */
    pre_uptime: number | null
    /**
     * Uptime after reboot (seconds)
     */
    post_uptime: number | null
    /**
     * Hashrate before reboot (H/s)
     */
    pre_hashrate: number | null
    /**
     * Hashrate after reboot (H/s)
     */
    post_hashrate: number | null
    /**
     * Pre-reboot snapshot collection time (ISO 8601)
     */
    pre_period: string | null
    /**
     * Post-reboot snapshot collection time (ISO 8601)
     */
    post_period: string | null
    /**
     * Power consumption before reboot (watts)
     */
    pre_wattage: number | null
    /**
     * Power consumption after reboot (watts)
     */
    post_wattage: number | null
    /**
     * Average board temperature before reboot (celsius)
     */
    pre_temp: number | null
    /**
     * Average board temperature after reboot (celsius)
     */
    post_temp: number | null
    /**
     * Anomaly bitmask before reboot. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
     */
    pre_anomaly_flags: number | null
    /**
     * Anomaly bitmask after reboot. Bits: 0=fan, 1=power, 2=temperature, 3=hashboard, 4=network, 5=firmware, 6=unknown, 8=control_board, 9=pool.
     */
    post_anomaly_flags: number | null
    /**
     * Mining mode before reboot (e.g. normal, sleep, low)
     */
    pre_mining_mode: string | null
    /**
     * Mining mode after reboot (e.g. normal, sleep, low)
     */
    post_mining_mode: string | null
    /**
     * Record creation time (ISO 8601)
     */
    created_at: string | null
    /**
     * Average hashrate 30–5 minutes before reboot (H/s); null when the window has no history
     */
    before_avg_hashrate: number | null
    /**
     * Average hashrate 15–60 minutes after reboot (H/s); null when the window has no history
     */
    after_avg_hashrate: number | null
  }[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface ListMinerPoolDiffsInput {
  workspace_id: string
  farm_id: string
  /**
   * Start time for the history data in ISO 8601 format with timezone offset.
   */
  from_time: string
  /**
   * End time for the history data in ISO 8601 format with timezone offset.
   */
  to_time: string
  /**
   * Time resolution of the returned snapshots.
   * - `10min`: max range 1 day (144 data points). Requires miner_id (single-miner queries only).
   * - `hour` (default): max range 7 days (168 data points).
   * - `day`: max range 90 days (90 data points).
   * - `week`: max range 365 days (52 data points).
   */
  granularity?: "10min" | "hour" | "day" | "week"
}
/**
 * Complete miner history record before the change
 */
export type MinerHistoryRecord = {
  [k: string]: unknown
} | null
/**
 * Complete miner history record after the change
 */
export type MinerHistoryRecord1 = {
  [k: string]: unknown
} | null
export interface ListMinerPoolDiffsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerPoolDiff[]
  /**
   * Error object (null on success)
   */
  error: null
}
export interface MinerPoolDiff {
  /**
   * Miner identifier
   */
  miner_id: string
  before_record: MinerHistoryRecord
  after_record: MinerHistoryRecord1
  /**
   * Summary of changes between the two time points
   */
  changes: {
    /**
     * Pool URL changes
     */
    pool_url: {
      /**
       * Value before the change
       */
      before: string | null
      /**
       * Value after the change
       */
      after: string | null
      /**
       * Whether the field has changed
       */
      changed: boolean
    }
    /**
     * Worker ID changes
     */
    worker_id: {
      /**
       * Value before the change
       */
      before: string | null
      /**
       * Value after the change
       */
      after: string | null
      /**
       * Whether the field has changed
       */
      changed: boolean
    }
  }
}
export interface ListAgentsInput {
  workspace_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
}
export interface ListAgentsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: Agent[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface Agent {
  /**
   * Agent Id (uuid generated by nonce system)
   */
  id: string
  /**
   * Farm Id (uuid generated by nonce system)
   */
  farm_id: string
  /**
   * Workspace Id
   */
  workspace_id: string
  /**
   * Status of the agent
   */
  status: string | null
  /**
   * Timestamp of agent last online. ISO Format
   */
  last_online_at: string | null
  /**
   * Agent version
   */
  version: string | null
  /**
   * Agent uptime in seconds
   */
  uptime: number | null
  /**
   * Timestamp of last updated. ISO Format
   */
  last_updated_at: string | null
}
export interface SearchAgentsInput {
  workspace_id: string
  /**
   * Enum or ID filter operators. Provide at least one operator.
   */
  farm_id?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  /**
   * Enum or ID filter operators. Provide at least one operator.
   */
  status?: {
    eq?: string
    ne?: string
    in?: string[]
    nin?: string[]
  }
  page?: number
  limit?: number
}
export interface SearchAgentsOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: Agent[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface ListTaskBatchesInput {
  workspace_id: string
  farm_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Filter by task name. Supports multiple values separated by comma. Task or event type dispatched to miners or agents. Execution types: `miner.system.reboot`, `miner.log.get`, `miner.light.update`, `miner.power_mode.update`, `miner.pool.update`, `miner.pool.lock`, `miner.firmware.update`, `agent.scan.create`, `agent.self.update`. Event types: `miner.tags.update`, `miner.record.delete`, `miner.rack_location.update`.
   */
  task_name?: (
    | "agent.scan.create"
    | "agent.ip_diagnosis.create"
    | "agent.self.update"
    | "miner.system.reboot"
    | "miner.log.get"
    | "miner.light.update"
    | "miner.power_mode.update"
    | "miner.pool.update"
    | "miner.pool.lock"
    | "miner.firmware.update"
    | "miner.tags.update"
    | "miner.record.delete"
    | "miner.rack_location.update"
  )[]
}
export interface ListTaskBatchesOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: TaskBatchSummary[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface TaskBatchSummary {
  /**
   * Miner task batch ID
   */
  batch_id: string
  /**
   * Miner task name
   */
  task_name:
    | "agent.scan.create"
    | "agent.ip_diagnosis.create"
    | "agent.self.update"
    | "miner.system.reboot"
    | "miner.log.get"
    | "miner.light.update"
    | "miner.power_mode.update"
    | "miner.pool.update"
    | "miner.pool.lock"
    | "miner.firmware.update"
    | "miner.tags.update"
    | "miner.record.delete"
    | "miner.rack_location.update"
  /**
   * Aggregate status of a task batch. `pending` = at least one task is still running; `succeed` = all tasks succeeded; `failed` = all tasks failed, timed out, or were cancelled; `partial_succeed` = finished with a mix of success and failure.
   */
  status: "pending" | "succeed" | "failed" | "partial_succeed"
  /**
   * Number of tasks in the batch
   */
  task_count: number
  /**
   * Number of succeeded tasks
   */
  succeed_count: number
  /**
   * Number of failed tasks
   */
  failed_count: number
  /**
   * Task parameters (JSON). Structure varies by task_name.
   */
  task_params: {
    [k: string]: unknown
  } | null
  /**
   * Automation trigger context. Keys: trigger ({predicateField, predicateValue}), automation ({id, name}), filterSummary ({total, passed, skippedUptime?, skippedAnomaly?, skippedNonNormal?, skippedRebootLimit?, skippedTemperature?, temperatureBypassedZeroHashrate?}). filterSummary shows how many miners were evaluated vs filtered at each stage — use it to identify automation filtering bottlenecks. Null for manually created batches.
   */
  metadata?: {
    [k: string]: unknown
  } | null
  created_by: Actor
  /**
   * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
   */
  created_at: string
}
export interface CreateTaskBatchMinerSystemRebootInput {
  workspace_id: string
  farm_id: string
  /**
   * Reboot miner ASIC. Brief downtime. Use after firmware update or when miner is unresponsive.
   */
  task_name: "miner.system.reboot"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Reboot parameters (optional).
   */
  params?: {
    /**
     * Force reboot (optional)
     */
    force?: boolean
  }
}
export interface CreateTaskBatchMinerSystemRebootOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface MinerTaskBatch {
  /**
   * Miner task batch ID
   */
  batch_id: string
  /**
   * Miner task name
   */
  task_name:
    | "agent.scan.create"
    | "agent.ip_diagnosis.create"
    | "agent.self.update"
    | "miner.system.reboot"
    | "miner.log.get"
    | "miner.light.update"
    | "miner.power_mode.update"
    | "miner.pool.update"
    | "miner.pool.lock"
    | "miner.firmware.update"
    | "miner.tags.update"
    | "miner.record.delete"
    | "miner.rack_location.update"
  /**
   * Number of tasks in the batch
   */
  task_count: number
  /**
   * Task parameters (JSON). Structure varies by task_name.
   */
  task_params: {
    [k: string]: unknown
  } | null
  created_by: Actor
  /**
   * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
   */
  created_at: string
}
export interface CreateTaskBatchMeta {
  summary: {
    created_count: number
    skipped_count: number
  }
  skipped?: {
    /**
     * Reason a miner was skipped during task batch creation. `no_change` = miner is already in the requested state; `unsupported_mode` = miner hardware does not support the requested mode; `miner_not_found` = miner id was not found in the workspace or farm; `unstable_miner` = miner row is flagged unstable and cannot accept actions.
     */
    reason: "no_change" | "unsupported_mode" | "miner_not_found" | "unstable_miner"
    message: string
    miner_ids: string[]
  }[]
}
export interface CreateTaskBatchMinerLogGetInput {
  workspace_id: string
  farm_id: string
  /**
   * Collect diagnostic logs from miner ASIC. Dispatches a command to the device; a signed download URL is returned on task success.
   */
  task_name: "miner.log.get"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  params?: {
    [k: string]: unknown
  }
}
export interface CreateTaskBatchMinerLogGetOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerLightUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Toggle miner LED indicator. Use for physical identification on the rack.
   */
  task_name: "miner.light.update"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Light mode parameters.
   */
  params: {
    /**
     * Miner status LED mode. `on` turns the indicator light on; `off` turns it off.
     */
    mode: "on" | "off"
  }
}
export interface CreateTaskBatchMinerLightUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerPowerModeUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Switch miner mining power mode. Affects hashrate and power consumption.
   */
  task_name: "miner.power_mode.update"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Mining mode parameters.
   */
  params: {
    /**
     * Mining performance mode level or firmware preset name
     */
    mode:
      | (
          | "low"
          | "normal"
          | "high"
          | "sleep"
          | "J/T 19.0, Hashrate ~125TH/s"
          | "J/T 20.0, Hashrate ~135TH/s"
          | "J/T 21.0, Hashrate ~145TH/s"
          | "J/T 21.5, Hashrate ~155TH/s"
          | "J/T 22.0, Hashrate ~165TH/s"
          | "J/T 22.5, Hashrate ~170TH/s"
          | "J/T 23.0, Hashrate ~175TH/s"
          | "5600W"
          | "5800W"
          | "6000W"
          | "6200W"
          | "6400W"
          | "6600W"
        )
      | string
  }
}
export interface CreateTaskBatchMinerPowerModeUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerFirmwareUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Flash firmware to miner. Extended downtime; miner reboots after install.
   */
  task_name: "miner.firmware.update"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Firmware update parameters.
   */
  params: {
    /**
     * URL to the firmware file
     */
    firmware_url: string
  }
}
export interface CreateTaskBatchMinerFirmwareUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerPoolLockInput {
  workspace_id: string
  farm_id: string
  /**
   * Lock or unlock miner pool configuration via auth package. Prevents unauthorized pool changes while locked.
   */
  task_name: "miner.pool.lock"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Pool lock parameters.
   */
  params: {
    /**
     * URL to the auth package file
     */
    firmware_url: string
    /**
     * Pool lock action
     */
    action: "lock" | "unlock"
  }
}
export interface CreateTaskBatchMinerPoolLockOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchAgentScanCreateInput {
  workspace_id: string
  farm_id: string
  /**
   * Trigger agent network scan to discover miners. Long-running; populates miner inventory on completion.
   */
  task_name: "agent.scan.create"
  /**
   * Agent scan parameters (optional).
   */
  params?: {
    /**
     * IP ranges to scan (optional). If omitted, agent scans all configured ranges.
     */
    ip_ranges?: {
      /**
       * IP range record ID
       */
      id: string
      /**
       * IP range in CIDR notation
       */
      range: string
      /**
       * Whether to continue scanning this range periodically (optional)
       */
      auto_scan?: boolean
    }[]
  }
}
export interface CreateTaskBatchAgentScanCreateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchAgentIpDiagnosisCreateInput {
  workspace_id: string
  farm_id: string
  /**
   * Trigger agent IP diagnosis and upload a CSV report. Uses local diagnostic context first unless refresh is requested.
   */
  task_name: "agent.ip_diagnosis.create"
  /**
   * IP diagnosis parameters.
   */
  params: {
    /**
     * Diagnosis target scope. custom_only uses only custom targets; known_with_custom merges agent known IPs and custom targets; known_only uses only agent known IPs.
     */
    target_scope?: "custom_only" | "known_with_custom" | "known_only"
    /**
     * Custom diagnosis targets
     */
    custom_targets?: {
      /**
       * Optional custom target identifier
       */
      id?: string
      /**
       * Optional custom target label
       */
      label?: string
      /**
       * IPv4 address, CIDR, or hyphen range to diagnose
       */
      value: string
    }[]
    /**
     * Only perform ICMP ping checks when the agent probes targets without local context
     */
    ping_only?: boolean
  }
}
export interface CreateTaskBatchAgentIpDiagnosisCreateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchAgentSelfUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Trigger agent to self-upgrade to a newer binary. Agent restarts after install; brief control-plane downtime, no miner impact.
   */
  task_name: "agent.self.update"
  /**
   * Agent self-update parameters (optional). All fields default to agent-configured values when omitted.
   */
  params?: {
    /**
     * Agent binary download URL (optional). Agent uses its configured default when omitted.
     */
    binary_url?: string
    /**
     * Legacy MD5 checksum of the agent binary (optional). Kept as a supplementary integrity check and not used as the security authority.
     */
    md5?: string
    /**
     * Ed25519 detached signature of the agent binary. Required whenever binary_url is provided so the agent can authorize the remote self-update.
     */
    signature?: string
    /**
     * Target agent version (optional). Used by agent to validate upgrade payload.
     */
    target_version?: string
  }
}
export interface CreateTaskBatchAgentSelfUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerTagsUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Add or remove operator-managed tags on miners. Metadata-only; does not affect mining operation.
   */
  task_name: "miner.tags.update"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Tag update parameters.
   */
  params: {
    /**
     * Tags to add to every selected miner
     */
    add?: string[]
    /**
     * Tags to remove from every selected miner
     */
    remove?: string[]
    /**
     * Deprecated: accepted for backward compatibility but ignored.
     */
    comment?: string
  }
}
export interface CreateTaskBatchMinerTagsUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerRecordDeleteInput {
  workspace_id: string
  farm_id: string
  /**
   * Mark miner as deleted in inventory. Reversible only via database operation. Use after physical decommission.
   */
  task_name: "miner.record.delete"
  /**
   * Array of miner IDs to execute task on
   */
  miner_ids: string[]
  /**
   * Asset delete parameters (optional).
   */
  params?: {
    /**
     * Optional comment for the deletion
     */
    comment?: string
  }
}
export interface CreateTaskBatchMinerRecordDeleteOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface CreateTaskBatchMinerRackLocationUpdateInput {
  workspace_id: string
  farm_id: string
  /**
   * Update miner rack and position metadata in inventory. Metadata-only; does not affect mining operation.
   */
  task_name: "miner.rack_location.update"
  /**
   * Per-miner rack location updates. Unchanged miners are omitted from the array.
   */
  updates: {
    miner_id: string
    /**
     * Rack identifier (up to 50 chars). Null to clear.
     */
    rack: string | null
    /**
     * Slot position within the rack (non-negative integer). Null to clear.
     */
    position: number | null
  }[]
  params?: {
    [k: string]: unknown
  }
}
export interface CreateTaskBatchMinerRackLocationUpdateOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: MinerTaskBatch[]
  /**
   * Error object (null on success)
   */
  error: null
  meta?: CreateTaskBatchMeta
}
export interface SearchTaskBatchesInput {
  workspace_id: string
  farm_id: string
  /**
   * Enum or ID filter operators. Provide at least one operator.
   */
  status?: {
    /**
     * Aggregate status of a task batch. `pending` = at least one task is still running; `succeed` = all tasks succeeded; `failed` = all tasks failed, timed out, or were cancelled; `partial_succeed` = finished with a mix of success and failure.
     */
    eq?: "pending" | "succeed" | "failed" | "partial_succeed"
    /**
     * Aggregate status of a task batch. `pending` = at least one task is still running; `succeed` = all tasks succeeded; `failed` = all tasks failed, timed out, or were cancelled; `partial_succeed` = finished with a mix of success and failure.
     */
    ne?: "pending" | "succeed" | "failed" | "partial_succeed"
    in?: ("pending" | "succeed" | "failed" | "partial_succeed")[]
    nin?: ("pending" | "succeed" | "failed" | "partial_succeed")[]
  }
  /**
   * Enum or ID filter operators. Provide at least one operator.
   */
  task_name?: {
    /**
     * Task or event type dispatched to miners or agents. Execution types: `miner.system.reboot`, `miner.log.get`, `miner.light.update`, `miner.power_mode.update`, `miner.pool.update`, `miner.pool.lock`, `miner.firmware.update`, `agent.scan.create`, `agent.ip_diagnosis.create`, `agent.self.update`. Event types: `miner.tags.update`, `miner.record.delete`, `miner.rack_location.update`.
     */
    eq?:
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    /**
     * Task or event type dispatched to miners or agents. Execution types: `miner.system.reboot`, `miner.log.get`, `miner.light.update`, `miner.power_mode.update`, `miner.pool.update`, `miner.pool.lock`, `miner.firmware.update`, `agent.scan.create`, `agent.ip_diagnosis.create`, `agent.self.update`. Event types: `miner.tags.update`, `miner.record.delete`, `miner.rack_location.update`.
     */
    ne?:
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    in?: (
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    )[]
    nin?: (
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    )[]
  }
  /**
   * Actor type filter. Only `eq` operator supported; multi-type filtering is not available.
   */
  actor_type?: {
    /**
     * Actor type used to filter task batches by creator. `user` = batches created by human users through the Nonce app; `automation` = batches created by the Automation workflow system; `api` = batches created via private-api or connect-api tokens.
     */
    eq?: "user" | "automation" | "api"
  }
  /**
   * Date filter operators using ISO 8601 UTC strings. Provide at least one operator.
   */
  created_at?: {
    eq?: string
    gt?: string
    gte?: string
    lt?: string
    lte?: string
  }
  page?: number
  limit?: number
}
export interface SearchTaskBatchesOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: TaskBatchSummary[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface GetTaskBatchInput {
  workspace_id: string
  farm_id: string
  batch_id: string
}
export interface GetTaskBatchOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  data: {
    /**
     * Miner task batch ID
     */
    batch_id: string
    /**
     * Miner task name
     */
    task_name:
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    /**
     * Aggregate status of a task batch. `pending` = at least one task is still running; `succeed` = all tasks succeeded; `failed` = all tasks failed, timed out, or were cancelled; `partial_succeed` = finished with a mix of success and failure.
     */
    status: "pending" | "succeed" | "failed" | "partial_succeed"
    /**
     * Total number of tasks in the batch
     */
    task_count: number
    /**
     * Tasks enqueued but not yet picked up
     */
    created_count: number
    /**
     * Tasks accepted by agent, waiting in local queue
     */
    queuing_count: number
    /**
     * Tasks actively executing on the miner
     */
    pending_count: number
    /**
     * Tasks finished successfully
     */
    succeed_count: number
    /**
     * Tasks finished with an error
     */
    failed_count: number
    /**
     * Tasks that exceeded their execution deadline
     */
    timed_out_count: number
    /**
     * Tasks aborted before completion
     */
    cancelled_count: number
    /**
     * Task parameters (JSON). Structure varies by task_name.
     */
    task_params: {
      [k: string]: unknown
    } | null
    /**
     * Automation trigger context. Keys: trigger ({predicateField, predicateValue}), automation ({id, name}), filterSummary ({total, passed, skippedUptime?, skippedAnomaly?, skippedNonNormal?, skippedRebootLimit?, skippedTemperature?, temperatureBypassedZeroHashrate?}). filterSummary shows how many miners were evaluated vs filtered at each stage — use it to identify automation filtering bottlenecks. Null for manually created batches.
     */
    metadata?: {
      [k: string]: unknown
    } | null
    /**
     * Represents an entity that performs actions in the system (user, API key, or system)
     */
    created_by: {
      [k: string]: unknown
    } | null
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    created_at: string
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface GetTaskBatchTasksInput {
  workspace_id: string
  farm_id: string
  batch_id: string
  /**
   * Page number (default: 1)
   */
  page?: number
  /**
   * Number of items per page (default: 10, max: 10000)
   */
  pageSize?: number
  /**
   * Filter tasks by status
   */
  status?: "created" | "queuing" | "pending" | "succeed" | "failed" | "timed_out" | "cancelled"
}
export interface GetTaskBatchTasksOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  /**
   * Array of items
   */
  data: {
    /**
     * Miner task ID
     */
    id: string
    /**
     * Miner task batch ID
     */
    batch_id: string
    /**
     * Miner task name
     */
    task_name:
      | "agent.scan.create"
      | "agent.ip_diagnosis.create"
      | "agent.self.update"
      | "miner.system.reboot"
      | "miner.log.get"
      | "miner.light.update"
      | "miner.power_mode.update"
      | "miner.pool.update"
      | "miner.pool.lock"
      | "miner.firmware.update"
      | "miner.tags.update"
      | "miner.record.delete"
      | "miner.rack_location.update"
    /**
     * Miner Id
     */
    miner_id?: string | null
    /**
     * Task execution status. `created` = enqueued but not yet picked up by an agent; `queuing` = accepted by the agent and waiting in its local queue; `pending` = actively executing on the miner; `succeed` = finished successfully; `failed` = finished with an error; `timed_out` = exceeded its execution deadline; `cancelled` = aborted before completion.
     */
    status: "created" | "queuing" | "pending" | "succeed" | "failed" | "timed_out" | "cancelled"
    /**
     * Task parameters (JSON)
     */
    params?: {
      [k: string]: unknown
    } | null
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    created_at: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    queuing_at?: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    pending_at?: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    succeed_at?: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    failed_at?: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    timed_out_at?: string
    /**
     * This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
     */
    cancelled_at?: string
    /**
     * Task execution result (JSON)
     */
    result?: {
      [k: string]: unknown
    }
    error?: {
      /**
       * Error message
       */
      message: string
    }
    /**
     * Miner log file download URL (signed URL from Supabase Storage, valid for 2 weeks)
     */
    log_download_url?: string | null
    /**
     * Miner log file size in bytes
     */
    log_file_size?: number | null
  }[]
  /**
   * Pagination metadata
   */
  pagination: {
    /**
     * Total number of items
     */
    total: number
    /**
     * Maximum number of items per page
     */
    limit: number
    /**
     * Number of items to skip
     */
    offset: number
    /**
     * Whether there are more items after this page
     */
    hasNext: boolean
    /**
     * Whether there are items before this page
     */
    hasPrevious: boolean
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export interface ListWorkspacesInput {}
/**
 * Observed output from read-only MCP tool ListWorkspaces.
 */
export interface ListWorkspacesOutput {
  status: number
  data: {
    success: boolean
    data: {
      workspace_id: string
      workspace_name: string
      workspace_slug: string
      role: string
    }[]
    error: null
  }
}
export interface ListBtcNetworkHistoryInput {
  /**
   * Start of time range (ISO 8601). Defaults to 7 days ago.
   */
  from_time?: string
  /**
   * End of time range (ISO 8601). Defaults to now.
   */
  to_time?: string
}
export interface ListBtcNetworkHistoryOutput {
  /**
   * Indicates if the request was successful
   */
  success: boolean
  data: {
    /**
     * Start of the queried time range (ISO 8601)
     */
    from: string
    /**
     * End of the queried time range (ISO 8601)
     */
    to: string
    /**
     * Time-series data points
     */
    snapshots: {
      /**
       * Period timestamp for this data point
       */
      period: string
      /**
       * Bitcoin price in USD
       */
      bitcoin_price: number
      /**
       * Hashprice in USD per PH/s per day
       */
      hashprice_usd: number
      /**
       * Hashprice in BTC per PH/s per day
       */
      hashprice_btc: number
      /**
       * Network hashrate in EH/s
       */
      network_hashrate: number
      /**
       * Network difficulty
       */
      network_difficulty: number
    }[]
  }
  /**
   * Error object (null on success)
   */
  error: null
}
export const nonceToolDefinitions = [
  {
    "destructive": false,
    "methodName": "listFarms",
    "name": "ListFarms",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listMiners",
    "name": "ListMiners",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "searchMiners",
    "name": "SearchMiners",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "getMinerStats",
    "name": "GetMinerStats",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listFarmMetricsHistory",
    "name": "ListFarmMetricsHistory",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listFarmEnergyHistory",
    "name": "ListFarmEnergyHistory",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listMinerHistory",
    "name": "ListMinerHistory",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "getMinerTasks",
    "name": "GetMinerTasks",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listMinerRebootEvents",
    "name": "ListMinerRebootEvents",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "getMinerRebootEvents",
    "name": "GetMinerRebootEvents",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listMinerPoolDiffs",
    "name": "ListMinerPoolDiffs",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listAgents",
    "name": "ListAgents",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "searchAgents",
    "name": "SearchAgents",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listTaskBatches",
    "name": "ListTaskBatches",
    "readOnly": true
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerSystemReboot",
    "name": "CreateTaskBatch_MinerSystemReboot",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerLogGet",
    "name": "CreateTaskBatch_MinerLogGet",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerLightUpdate",
    "name": "CreateTaskBatch_MinerLightUpdate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerPowerModeUpdate",
    "name": "CreateTaskBatch_MinerPower_modeUpdate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerFirmwareUpdate",
    "name": "CreateTaskBatch_MinerFirmwareUpdate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerPoolLock",
    "name": "CreateTaskBatch_MinerPoolLock",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchAgentScanCreate",
    "name": "CreateTaskBatch_AgentScanCreate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchAgentIpDiagnosisCreate",
    "name": "CreateTaskBatch_AgentIp_diagnosisCreate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchAgentSelfUpdate",
    "name": "CreateTaskBatch_AgentSelfUpdate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerTagsUpdate",
    "name": "CreateTaskBatch_MinerTagsUpdate",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerRecordDelete",
    "name": "CreateTaskBatch_MinerRecordDelete",
    "readOnly": false
  },
  {
    "destructive": true,
    "methodName": "createTaskBatchMinerRackLocationUpdate",
    "name": "CreateTaskBatch_MinerRack_locationUpdate",
    "readOnly": false
  },
  {
    "destructive": false,
    "methodName": "searchTaskBatches",
    "name": "SearchTaskBatches",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "getTaskBatch",
    "name": "GetTaskBatch",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "getTaskBatchTasks",
    "name": "GetTaskBatchTasks",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listWorkspaces",
    "name": "ListWorkspaces",
    "readOnly": true
  },
  {
    "destructive": false,
    "methodName": "listBtcNetworkHistory",
    "name": "ListBtcNetworkHistory",
    "readOnly": true
  }
] as const

export interface NonceCallOptions {
  signal?: AbortSignal
  timeoutMs?: number
}

export type NonceReadonlyCallOptions = NonceCallOptions

export interface NonceDestructiveCallOptions extends NonceCallOptions {
  confirmDestructive: true
  confirmation: string
}

export interface NonceClientOptions {
  allowDestructive?: boolean
  profile?: string
}

export interface NonceClient {
  close(): Promise<void>
  listFarms(input: ListFarmsInput, options?: NonceReadonlyCallOptions): Promise<ListFarmsOutput>
  listMiners(input: ListMinersInput, options?: NonceReadonlyCallOptions): Promise<ListMinersOutput>
  searchMiners(input: SearchMinersInput, options?: NonceReadonlyCallOptions): Promise<SearchMinersOutput>
  getMinerStats(input: GetMinerStatsInput, options?: NonceReadonlyCallOptions): Promise<GetMinerStatsOutput>
  listFarmMetricsHistory(input: ListFarmMetricsHistoryInput, options?: NonceReadonlyCallOptions): Promise<ListFarmMetricsHistoryOutput>
  listFarmEnergyHistory(input: ListFarmEnergyHistoryInput, options?: NonceReadonlyCallOptions): Promise<ListFarmEnergyHistoryOutput>
  listMinerHistory(input: ListMinerHistoryInput, options?: NonceReadonlyCallOptions): Promise<ListMinerHistoryOutput>
  getMinerTasks(input: GetMinerTasksInput, options?: NonceReadonlyCallOptions): Promise<GetMinerTasksOutput>
  listMinerRebootEvents(input: ListMinerRebootEventsInput, options?: NonceReadonlyCallOptions): Promise<ListMinerRebootEventsOutput>
  getMinerRebootEvents(input: GetMinerRebootEventsInput, options?: NonceReadonlyCallOptions): Promise<GetMinerRebootEventsOutput>
  listMinerPoolDiffs(input: ListMinerPoolDiffsInput, options?: NonceReadonlyCallOptions): Promise<ListMinerPoolDiffsOutput>
  listAgents(input: ListAgentsInput, options?: NonceReadonlyCallOptions): Promise<ListAgentsOutput>
  searchAgents(input: SearchAgentsInput, options?: NonceReadonlyCallOptions): Promise<SearchAgentsOutput>
  listTaskBatches(input: ListTaskBatchesInput, options?: NonceReadonlyCallOptions): Promise<ListTaskBatchesOutput>
  createTaskBatchMinerSystemReboot(input: CreateTaskBatchMinerSystemRebootInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerSystemRebootOutput>
  createTaskBatchMinerLogGet(input: CreateTaskBatchMinerLogGetInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerLogGetOutput>
  createTaskBatchMinerLightUpdate(input: CreateTaskBatchMinerLightUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerLightUpdateOutput>
  createTaskBatchMinerPowerModeUpdate(input: CreateTaskBatchMinerPowerModeUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerPowerModeUpdateOutput>
  createTaskBatchMinerFirmwareUpdate(input: CreateTaskBatchMinerFirmwareUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerFirmwareUpdateOutput>
  createTaskBatchMinerPoolLock(input: CreateTaskBatchMinerPoolLockInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerPoolLockOutput>
  createTaskBatchAgentScanCreate(input: CreateTaskBatchAgentScanCreateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchAgentScanCreateOutput>
  createTaskBatchAgentIpDiagnosisCreate(input: CreateTaskBatchAgentIpDiagnosisCreateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchAgentIpDiagnosisCreateOutput>
  createTaskBatchAgentSelfUpdate(input: CreateTaskBatchAgentSelfUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchAgentSelfUpdateOutput>
  createTaskBatchMinerTagsUpdate(input: CreateTaskBatchMinerTagsUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerTagsUpdateOutput>
  createTaskBatchMinerRecordDelete(input: CreateTaskBatchMinerRecordDeleteInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerRecordDeleteOutput>
  createTaskBatchMinerRackLocationUpdate(input: CreateTaskBatchMinerRackLocationUpdateInput, options: NonceDestructiveCallOptions): Promise<CreateTaskBatchMinerRackLocationUpdateOutput>
  searchTaskBatches(input: SearchTaskBatchesInput, options?: NonceReadonlyCallOptions): Promise<SearchTaskBatchesOutput>
  getTaskBatch(input: GetTaskBatchInput, options?: NonceReadonlyCallOptions): Promise<GetTaskBatchOutput>
  getTaskBatchTasks(input: GetTaskBatchTasksInput, options?: NonceReadonlyCallOptions): Promise<GetTaskBatchTasksOutput>
  listWorkspaces(input?: ListWorkspacesInput, options?: NonceReadonlyCallOptions): Promise<ListWorkspacesOutput>
  listBtcNetworkHistory(input?: ListBtcNetworkHistoryInput, options?: NonceReadonlyCallOptions): Promise<ListBtcNetworkHistoryOutput>
}

export interface NonceMethodSignatures {
  listFarms: {
    destructive: false
    input: ListFarmsInput
    output: ListFarmsOutput
  }
  listMiners: {
    destructive: false
    input: ListMinersInput
    output: ListMinersOutput
  }
  searchMiners: {
    destructive: false
    input: SearchMinersInput
    output: SearchMinersOutput
  }
  getMinerStats: {
    destructive: false
    input: GetMinerStatsInput
    output: GetMinerStatsOutput
  }
  listFarmMetricsHistory: {
    destructive: false
    input: ListFarmMetricsHistoryInput
    output: ListFarmMetricsHistoryOutput
  }
  listFarmEnergyHistory: {
    destructive: false
    input: ListFarmEnergyHistoryInput
    output: ListFarmEnergyHistoryOutput
  }
  listMinerHistory: {
    destructive: false
    input: ListMinerHistoryInput
    output: ListMinerHistoryOutput
  }
  getMinerTasks: {
    destructive: false
    input: GetMinerTasksInput
    output: GetMinerTasksOutput
  }
  listMinerRebootEvents: {
    destructive: false
    input: ListMinerRebootEventsInput
    output: ListMinerRebootEventsOutput
  }
  getMinerRebootEvents: {
    destructive: false
    input: GetMinerRebootEventsInput
    output: GetMinerRebootEventsOutput
  }
  listMinerPoolDiffs: {
    destructive: false
    input: ListMinerPoolDiffsInput
    output: ListMinerPoolDiffsOutput
  }
  listAgents: {
    destructive: false
    input: ListAgentsInput
    output: ListAgentsOutput
  }
  searchAgents: {
    destructive: false
    input: SearchAgentsInput
    output: SearchAgentsOutput
  }
  listTaskBatches: {
    destructive: false
    input: ListTaskBatchesInput
    output: ListTaskBatchesOutput
  }
  createTaskBatchMinerSystemReboot: {
    destructive: true
    input: CreateTaskBatchMinerSystemRebootInput
    output: CreateTaskBatchMinerSystemRebootOutput
  }
  createTaskBatchMinerLogGet: {
    destructive: true
    input: CreateTaskBatchMinerLogGetInput
    output: CreateTaskBatchMinerLogGetOutput
  }
  createTaskBatchMinerLightUpdate: {
    destructive: true
    input: CreateTaskBatchMinerLightUpdateInput
    output: CreateTaskBatchMinerLightUpdateOutput
  }
  createTaskBatchMinerPowerModeUpdate: {
    destructive: true
    input: CreateTaskBatchMinerPowerModeUpdateInput
    output: CreateTaskBatchMinerPowerModeUpdateOutput
  }
  createTaskBatchMinerFirmwareUpdate: {
    destructive: true
    input: CreateTaskBatchMinerFirmwareUpdateInput
    output: CreateTaskBatchMinerFirmwareUpdateOutput
  }
  createTaskBatchMinerPoolLock: {
    destructive: true
    input: CreateTaskBatchMinerPoolLockInput
    output: CreateTaskBatchMinerPoolLockOutput
  }
  createTaskBatchAgentScanCreate: {
    destructive: true
    input: CreateTaskBatchAgentScanCreateInput
    output: CreateTaskBatchAgentScanCreateOutput
  }
  createTaskBatchAgentIpDiagnosisCreate: {
    destructive: true
    input: CreateTaskBatchAgentIpDiagnosisCreateInput
    output: CreateTaskBatchAgentIpDiagnosisCreateOutput
  }
  createTaskBatchAgentSelfUpdate: {
    destructive: true
    input: CreateTaskBatchAgentSelfUpdateInput
    output: CreateTaskBatchAgentSelfUpdateOutput
  }
  createTaskBatchMinerTagsUpdate: {
    destructive: true
    input: CreateTaskBatchMinerTagsUpdateInput
    output: CreateTaskBatchMinerTagsUpdateOutput
  }
  createTaskBatchMinerRecordDelete: {
    destructive: true
    input: CreateTaskBatchMinerRecordDeleteInput
    output: CreateTaskBatchMinerRecordDeleteOutput
  }
  createTaskBatchMinerRackLocationUpdate: {
    destructive: true
    input: CreateTaskBatchMinerRackLocationUpdateInput
    output: CreateTaskBatchMinerRackLocationUpdateOutput
  }
  searchTaskBatches: {
    destructive: false
    input: SearchTaskBatchesInput
    output: SearchTaskBatchesOutput
  }
  getTaskBatch: {
    destructive: false
    input: GetTaskBatchInput
    output: GetTaskBatchOutput
  }
  getTaskBatchTasks: {
    destructive: false
    input: GetTaskBatchTasksInput
    output: GetTaskBatchTasksOutput
  }
  listWorkspaces: {
    destructive: false
    input: ListWorkspacesInput
    output: ListWorkspacesOutput
  }
  listBtcNetworkHistory: {
    destructive: false
    input: ListBtcNetworkHistoryInput
    output: ListBtcNetworkHistoryOutput
  }
}
